"""Configuration settings for the AI Code Review system."""

from pathlib import Path
from typing import Dict, Any

# Project paths
PROJECT_DIR = Path(__file__).parent.parent
KNOWLEDGE_DIR = PROJECT_DIR / "knowledge"
STORAGE_DIR = PROJECT_DIR / "storage"

# Database settings
DB_FILE = STORAGE_DIR / "agents.db"
DB_URL = "postgresql://ai:ai@localhost:5432/ai"

# Model settings
DEFAULT_MODEL = "gpt-4o"
DEFAULT_TEMPERATURE = 0.7

# Agent settings
MAX_ITERATIONS = 2
QUALITY_THRESHOLDS = {
    "code_review": 85,
    "test_coverage": 90,
    "security_score": 95
}

# Task settings
TASK_PRIORITIES = ["high", "medium", "low"]
TASK_TYPES = ["feature", "bug", "enhancement"]

# Knowledge base paths
CODE_PATTERNS_PATH = KNOWLEDGE_DIR / "code_patterns"
TEST_PATTERNS_PATH = KNOWLEDGE_DIR / "test_patterns"
REVIEW_PATTERNS_PATH = KNOWLEDGE_DIR / "review_patterns"
SECURITY_KB_PATH = KNOWLEDGE_DIR / "security"
PERFORMANCE_KB_PATH = KNOWLEDGE_DIR / "performance"

# Documentation URLs from Phidata docs
DOCUMENTATION_URLS = [
    "https://docs.phidata.com/agent-ui",
    "https://docs.phidata.com/agents/memory",
    "https://docs.phidata.com/agents/prompts",
    "https://docs.phidata.com/agents/reasoning",
    "https://docs.phidata.com/agents/storage",
    "https://docs.phidata.com/agents/structured-output",
    "https://docs.phidata.com/agents/teams",
    "https://docs.phidata.com/agents/tools",
    "https://docs.phidata.com/changelog/overview",
    "https://docs.phidata.com/embedder/azure_openai",
    "https://docs.phidata.com/embedder/fireworks",
    "https://docs.phidata.com/embedder/gemini",
    "https://docs.phidata.com/embedder/huggingface",
    "https://docs.phidata.com/embedder/introduction",
    "https://docs.phidata.com/embedder/mistral",
    "https://docs.phidata.com/embedder/ollama",
    "https://docs.phidata.com/embedder/openai",
    "https://docs.phidata.com/embedder/qdrant_fastembed",
    "https://docs.phidata.com/embedder/sentencetransformers",
    "https://docs.phidata.com/embedder/together",
    "https://docs.phidata.com/embedder/voyageai",
    "https://docs.phidata.com/examples/agents/agent-team",
    "https://docs.phidata.com/examples/agents/data-analyst",
    "https://docs.phidata.com/examples/agents/finance-agent",
    "https://docs.phidata.com/examples/agents/generate-image-agent",
    "https://docs.phidata.com/examples/agents/image-agent",
    "https://docs.phidata.com/examples/agents/python-agent",
    "https://docs.phidata.com/examples/agents/python-function-agent",
    "https://docs.phidata.com/examples/agents/reasoning-agent",
    "https://docs.phidata.com/examples/agents/structured-output",
    "https://docs.phidata.com/examples/agents/web-search",
    "https://docs.phidata.com/examples/how-to/use-cookbook",
    "https://docs.phidata.com/examples/integrations/chroma",
    "https://docs.phidata.com/examples/integrations/composio",
    "https://docs.phidata.com/examples/integrations/lancedb",
    "https://docs.phidata.com/examples/integrations/pgvector",
    "https://docs.phidata.com/examples/integrations/pinecone",
    "https://docs.phidata.com/examples/integrations/portkey",
    "https://docs.phidata.com/examples/integrations/qdrant",
    "https://docs.phidata.com/examples/integrations/singlestore",
    "https://docs.phidata.com/examples/introduction",
    "https://docs.phidata.com/examples/provider/aws_bedrock",
    "https://docs.phidata.com/examples/provider/azure",
    "https://docs.phidata.com/examples/provider/claude",
    "https://docs.phidata.com/examples/provider/cohere",
    "https://docs.phidata.com/examples/provider/deepseek",
    "https://docs.phidata.com/examples/provider/fireworks",
    "https://docs.phidata.com/examples/provider/gemini",
    "https://docs.phidata.com/examples/provider/groq",
    "https://docs.phidata.com/examples/provider/huggingface",
    "https://docs.phidata.com/examples/provider/mistral",
    "https://docs.phidata.com/examples/provider/nvidia",
    "https://docs.phidata.com/examples/provider/ollama",
    "https://docs.phidata.com/examples/provider/openai",
    "https://docs.phidata.com/examples/provider/openrouter",
    "https://docs.phidata.com/examples/provider/sambanova",
    "https://docs.phidata.com/examples/provider/together",
    "https://docs.phidata.com/examples/provider/xai",
    "https://docs.phidata.com/examples/teams/hackernews",
    "https://docs.phidata.com/examples/teams/investment",
    "https://docs.phidata.com/examples/teams/journalist",
    "https://docs.phidata.com/examples/teams/research",
    "https://docs.phidata.com/examples/use-case/arxiv-research",
    "https://docs.phidata.com/examples/use-case/sql",
    "https://docs.phidata.com/examples/use-case/worldbuilding",
    "https://docs.phidata.com/faq/connecting-to-tableplus",
    "https://docs.phidata.com/faq/could-not-connect-to-docker",
    "https://docs.phidata.com/faq/environment_variables",
    "https://docs.phidata.com/faq/phi-auth",
    "https://docs.phidata.com/getting-help",
    "https://docs.phidata.com/how-to/install",
    "https://docs.phidata.com/knowledge/arxiv",
    "https://docs.phidata.com/knowledge/combined",
    "https://docs.phidata.com/knowledge/csv",
    "https://docs.phidata.com/knowledge/document",
    "https://docs.phidata.com/knowledge/docx",
    "https://docs.phidata.com/knowledge/introduction",
    "https://docs.phidata.com/knowledge/json",
    "https://docs.phidata.com/knowledge/langchain",
    "https://docs.phidata.com/knowledge/llamaindex",
    "https://docs.phidata.com/knowledge/pdf",
    "https://docs.phidata.com/knowledge/pdf-url",
    "https://docs.phidata.com/knowledge/s3_pdf",
    "https://docs.phidata.com/knowledge/s3_text",
    "https://docs.phidata.com/knowledge/text",
    "https://docs.phidata.com/knowledge/website",
    "https://docs.phidata.com/knowledge/wikipedia",
    "https://docs.phidata.com/migration/2-5-0",
    "https://docs.phidata.com/models/anthropic",
    "https://docs.phidata.com/models/aws-bedrock",
    "https://docs.phidata.com/models/azure",
    "https://docs.phidata.com/models/cohere",
    "https://docs.phidata.com/models/deepseek",
    "https://docs.phidata.com/models/fireworks",
    "https://docs.phidata.com/models/google_ai_studio",
    "https://docs.phidata.com/models/groq",
    "https://docs.phidata.com/models/huggingface",
    "https://docs.phidata.com/models/introduction",
    "https://docs.phidata.com/models/mistral",
    "https://docs.phidata.com/models/nvidia",
    "https://docs.phidata.com/models/ollama",
    "https://docs.phidata.com/models/openai",
    "https://docs.phidata.com/models/openai-like",
    "https://docs.phidata.com/models/openrouter",
    "https://docs.phidata.com/models/sambanova",
    "https://docs.phidata.com/models/together",
    "https://docs.phidata.com/models/xai",
    "https://docs.phidata.com/monitoring",
    "https://docs.phidata.com/reference/agent",
    "https://docs.phidata.com/reference/agents/duckdb",
    "https://docs.phidata.com/reference/agents/python",
    "https://docs.phidata.com/reference/cli/phi/auth",
    "https://docs.phidata.com/reference/cli/phi/config",
    "https://docs.phidata.com/reference/cli/phi/init",
    "https://docs.phidata.com/reference/cli/phi/patch",
    "https://docs.phidata.com/reference/cli/phi/reset",
    "https://docs.phidata.com/reference/cli/phi/restart",
    "https://docs.phidata.com/reference/cli/phi/set",
    "https://docs.phidata.com/reference/cli/phi/start",
    "https://docs.phidata.com/reference/cli/phi/stop",
    "https://docs.phidata.com/reference/cli/ws/config",
    "https://docs.phidata.com/reference/cli/ws/create",
    "https://docs.phidata.com/reference/cli/ws/delete",
    "https://docs.phidata.com/reference/cli/ws/down",
    "https://docs.phidata.com/reference/cli/ws/patch",
    "https://docs.phidata.com/reference/cli/ws/restart",
    "https://docs.phidata.com/reference/cli/ws/setup",
    "https://docs.phidata.com/reference/cli/ws/up",
    "https://docs.phidata.com/reference/kb/arxiv",
    "https://docs.phidata.com/reference/kb/base",
    "https://docs.phidata.com/reference/kb/combined",
    "https://docs.phidata.com/reference/kb/csv",
    "https://docs.phidata.com/reference/kb/document",
    "https://docs.phidata.com/reference/kb/docx",
    "https://docs.phidata.com/reference/kb/json",
    "https://docs.phidata.com/reference/kb/langchain",
    "https://docs.phidata.com/reference/kb/llamaindex",
    "https://docs.phidata.com/reference/kb/pdf",
    "https://docs.phidata.com/reference/kb/pdf-url",
    "https://docs.phidata.com/reference/kb/text",
    "https://docs.phidata.com/reference/kb/website",
    "https://docs.phidata.com/reference/kb/wikipedia",
    "https://docs.phidata.com/reference/model/aws",
    "https://docs.phidata.com/reference/model/azure",
    "https://docs.phidata.com/reference/model/base",
    "https://docs.phidata.com/reference/model/claude",
    "https://docs.phidata.com/reference/model/cohere",
    "https://docs.phidata.com/reference/model/deepseek",
    "https://docs.phidata.com/reference/model/fireworks",
    "https://docs.phidata.com/reference/model/gemini",
    "https://docs.phidata.com/reference/model/groq",
    "https://docs.phidata.com/reference/model/mistral",
    "https://docs.phidata.com/reference/model/ollama",
    "https://docs.phidata.com/reference/model/openai",
    "https://docs.phidata.com/reference/model/openrouter",
    "https://docs.phidata.com/reference/model/sambanova",
    "https://docs.phidata.com/reference/model/together",
    "https://docs.phidata.com/reference/storage/dynamodb",
    "https://docs.phidata.com/reference/storage/postgres",
    "https://docs.phidata.com/reference/storage/singlestore",
    "https://docs.phidata.com/reference/storage/sqlite",
    "https://docs.phidata.com/reference/vectordb/chromadb",
    "https://docs.phidata.com/reference/vectordb/lancedb",
    "https://docs.phidata.com/reference/vectordb/pgvector",
    "https://docs.phidata.com/reference/vectordb/pgvector2",
    "https://docs.phidata.com/reference/vectordb/pineconedb",
    "https://docs.phidata.com/reference/vectordb/qdrant",
    "https://docs.phidata.com/reference/vectordb/singlestore",
    "https://docs.phidata.com/storage/dynamodb",
    "https://docs.phidata.com/storage/introduction",
    "https://docs.phidata.com/storage/postgres",
    "https://docs.phidata.com/storage/singlestore",
    "https://docs.phidata.com/storage/sqlite",
    "https://docs.phidata.com/templates",
    "https://docs.phidata.com/templates/agent-api/run-aws",
    "https://docs.phidata.com/templates/agent-api/run-local",
    "https://docs.phidata.com/templates/agent-app/run-aws",
    "https://docs.phidata.com/templates/agent-app/run-local",
    "https://docs.phidata.com/templates/apps/examples",
    "https://docs.phidata.com/templates/apps/features",
    "https://docs.phidata.com/templates/apps/introduction",
    "https://docs.phidata.com/templates/how-to/ci-cd",
    "https://docs.phidata.com/templates/how-to/database-tables",
    "https://docs.phidata.com/templates/how-to/development-app",
    "https://docs.phidata.com/templates/how-to/domain-https",
    "https://docs.phidata.com/templates/how-to/env-vars",
    "https://docs.phidata.com/templates/how-to/format-and-validate",
    "https://docs.phidata.com/templates/how-to/git-repo",
    "https://docs.phidata.com/templates/how-to/install",
    "https://docs.phidata.com/templates/how-to/new-users",
    "https://docs.phidata.com/templates/how-to/production-app",
    "https://docs.phidata.com/templates/how-to/secrets",
    "https://docs.phidata.com/templates/how-to/ssh-access",
    "https://docs.phidata.com/templates/how-to/workspace-settings",
    "https://docs.phidata.com/templates/introduction",
    "https://docs.phidata.com/templates/resources/aws/ecs",
    "https://docs.phidata.com/templates/resources/aws/introduction",
    "https://docs.phidata.com/templates/resources/aws/rds",
    "https://docs.phidata.com/templates/resources/docker/container",
    "https://docs.phidata.com/templates/resources/docker/introduction",
    "https://docs.phidata.com/templates/resources/introduction",
    "https://docs.phidata.com/templates/workspace/introduction",
    "https://docs.phidata.com/templates/workspace/resources",
    "https://docs.phidata.com/templates/workspace/settings",
    "https://docs.phidata.com/tools/airflow",
    "https://docs.phidata.com/tools/apify",
    "https://docs.phidata.com/tools/arxiv",
    "https://docs.phidata.com/tools/aws_lambda",
    "https://docs.phidata.com/tools/calculator",
    "https://docs.phidata.com/tools/composio",
    "https://docs.phidata.com/tools/crawl4ai",
    "https://docs.phidata.com/tools/csv",
    "https://docs.phidata.com/tools/custom-toolkits",
    "https://docs.phidata.com/tools/dalle",
    "https://docs.phidata.com/tools/duckdb",
    "https://docs.phidata.com/tools/duckduckgo",
    "https://docs.phidata.com/tools/email",
    "https://docs.phidata.com/tools/exa",
    "https://docs.phidata.com/tools/file",
    "https://docs.phidata.com/tools/firecrawl",
    "https://docs.phidata.com/tools/functions",
    "https://docs.phidata.com/tools/github",
    "https://docs.phidata.com/tools/googlesearch",
    "https://docs.phidata.com/tools/hackernews",
    "https://docs.phidata.com/tools/introduction",
    "https://docs.phidata.com/tools/jina_reader",
    "https://docs.phidata.com/tools/jira",
    "https://docs.phidata.com/tools/mlx_transcribe",
    "https://docs.phidata.com/tools/models_labs",
    "https://docs.phidata.com/tools/newspaper",
    "https://docs.phidata.com/tools/newspaper4k",
    "https://docs.phidata.com/tools/openbb",
    "https://docs.phidata.com/tools/pandas",
    "https://docs.phidata.com/tools/phi",
    "https://docs.phidata.com/tools/postgres",
    "https://docs.phidata.com/tools/pubmed",
    "https://docs.phidata.com/tools/python",
    "https://docs.phidata.com/tools/resend",
    "https://docs.phidata.com/tools/searxng",
    "https://docs.phidata.com/tools/serpapi",
    "https://docs.phidata.com/tools/shell",
    "https://docs.phidata.com/tools/slack",
    "https://docs.phidata.com/tools/sleep",
    "https://docs.phidata.com/tools/spider",
    "https://docs.phidata.com/tools/sql",
    "https://docs.phidata.com/tools/tavily",
    "https://docs.phidata.com/tools/toolkits",
    "https://docs.phidata.com/tools/twitter",
    "https://docs.phidata.com/tools/website",
    "https://docs.phidata.com/tools/wikipedia",
    "https://docs.phidata.com/tools/yfinance",
    "https://docs.phidata.com/tools/youtube",
    "https://docs.phidata.com/tools/zendesk",
    "https://docs.phidata.com/tools/zoom",
    "https://docs.phidata.com/vectordb/chroma",
    "https://docs.phidata.com/vectordb/introduction",
    "https://docs.phidata.com/vectordb/lancedb",
    "https://docs.phidata.com/vectordb/pgvector",
    "https://docs.phidata.com/vectordb/pinecone",
    "https://docs.phidata.com/vectordb/qdrant",
    "https://docs.phidata.com/vectordb/singlestore",
    "https://docs.phidata.com/videos",
    "https://docs.phidata.com/workflows",
    "https://docs.phidata.com/workflows/introduction",
    "https://docs.phidata.com/workflows/news-report-generator",
    "https://docs.phidata.com/workflows/session-state",
    "https://docs.phidata.com/workflows/streaming"
    "https://docs.phidata.com/agents",
    "https://docs.phidata.com/agents/introduction",
    "https://docs.phidata.com/agents/knowledge"
]